PLUGIN_NAME=		umb
PLUGIN_VERSION=		1.20.6.12
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Integration of umb(4) with OPNsense
PLUGIN_MAINTAINER=	pierre@defora.net
PLUGIN_WWW=		https://www.defora.net/

.include "/usr/plugins/Mk/plugins.mk"
PLUGINSDIR=		/usr/plugins
